kind: pipeline
type: exec
name: tapan_exec_pipeline

steps:
- name: build_always
  image: plugins/docker
  settings:
    # username: tapanhalani
    # password: 
    repo: tapanhalani/nodejs-sample-app
    tags: latest
  