kind: pipeline
type: exec
name: tapan_exec_pipeline

steps:
- name: build_always
  image: plugins/docker
  settings:
    username:
      from_secret: username
    password:
      from_secret: password
    repo: tapanhalani/nodejs-sample-app
    tags: latest

---
kind: secret
name: username
get:
  path: tapan-docker-registry
  name: username

---
kind: secret
name: password
get:
  path: tapan-docker-registry
  name: password
  